baseURL = "https://brendanperry.github.io/"
title = "brendanperry.me"
theme = "PaperMod"

[taxonomies]
   tag = "tags"

[params]
env = "production"
title = "Brendan Perry"
description = "Personal Website"
keywords = [ "Blog", "Portfolio", "Software", "Brendan", "Perry", "Software Engineer", "Software Developer", "iOS" ]
author = "Brendan Perry"
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowCodeCopyButtons = true
disableScrollToTop = false
comments = false

  [params.label]
  text = "Brendan Perry"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Brendan Perry"
  subtitle = "Software Engineer"
  imageUrl = "/profilePicture.jpg"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "Headshot"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "projects"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/brendanperry"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/brendanperry"

  [[params.socialIcons]]
  name = "email"
  url = "https://keyserver.ubuntu.com/pks/lookup?search=brendan%40brendanperry.me&fingerprint=on&op=index"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

