baseURL = "https://brendanperry.github.io/"
title = "brendanperry.me"
theme = "PaperMod"

[params]
env = "production"
title = "Brendan Perry"
description = "Personal Website"
keywords = [ "Blog", "Portfolio", "Software", "Brendan", "Perry", "Software Engineer", "Software Developer", "iOS" ]
author = "Brendan Perry"
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowCodeCopyButtons = true
disableScrollToTop = false
comments = false

[params.label]
text = "Brendan Perry"
iconHeight = 35

[params.profileMode]
enabled = true
title = "Brendan Perry"
subtitle = "Software Engineer"
imageUrl = "/profilePicture.jpg"
imageWidth = 200
imageHeight = 200
imageTitle = "Headshot"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Have an app idea?"
url = "https://perrysoftware.com"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/brendanperry"

[[params.socialIcons]]
name = "github"
url = "https://github.com/brendanperry"

[[params.socialIcons]]
name = "email"
url = "mailto://brendan@brendanperry.me"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

